import type { Template } from "@/types";

export const TEMPLATES: Template[] = [
  {
    id: "classic",
    name: "Classic",
    tags: ["retro", "timeless"],
    format: "both",
    backgroundColor: "#FFFFFF",
    borderColor: "#1A1410",
    borderWidth: 8,
    photoGap: 6,
    showDate: true,
    showCaption: false,
    textColor: "#1A1410",
    fontFamily: "serif",
  },
  {
    id: "y2k",
    name: "Y2K",
    tags: ["fun", "girly", "2000s"],
    format: "both",
    backgroundColor: "#FFB3DE",
    borderColor: "#FF69B4",
    borderWidth: 10,
    photoGap: 6,
    showDate: false,
    showCaption: true,
    textColor: "#FFFFFF",
  },
  {
    id: "film",
    name: "Film",
    tags: ["analog", "lo-fi", "warm"],
    format: "both",
    backgroundColor: "#F5E6D0",
    borderColor: "#2C1810",
    borderWidth: 12,
    photoGap: 2,
    showDate: true,
    showCaption: false,
    textColor: "#2C1810",
    fontFamily: "mono",
  },
  {
    id: "dark",
    name: "Dark",
    tags: ["moody", "aesthetic"],
    format: "both",
    backgroundColor: "#0A0A0A",
    borderColor: "#C9A84C",
    borderWidth: 8,
    photoGap: 4,
    showDate: false,
    showCaption: false,
    textColor: "#C9A84C",
  },
  {
    id: "pastel",
    name: "Pastel",
    tags: ["soft", "cute", "dreamy"],
    format: "both",
    backgroundColor: "#E8F4F8",
    borderColor: "#B8D8E8",
    borderWidth: 10,
    photoGap: 6,
    showDate: true,
    showCaption: false,
    textColor: "#6B9EAF",
    photoBorderRadius: 8,
  },
];

export const getTemplateById = (id: string) =>
  TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
