import { Template } from "../types";

export const TEMPLATES: Template[] = [
  {
    id: "classic",
    name: "Classic",
    tags: ["retro", "timeless"],
    format: "both",
    backgroundColor: "#FFFFFF",
    borderColor: "#000000",
    borderWidth: 8,
    borderRadius: 0,
    photoGap: 4,
    photoBorderRadius: 0,
    showDate: true,
    showCaption: true,
    dateFont: "SpaceMono-Bold",
    captionFont: "Caveat",
    textColor: "#000000",
    overlayKey: "classic-stamp",
    overlayOpacity: 1,
    thumbnail: "classic",
  },
  {
    id: "y2k",
    name: "Y2K",
    tags: ["fun", "girly", "2000s"],
    format: "both",
    backgroundColor: "#FFB3DE",
    borderColor: "#FF69B4",
    borderWidth: 10,
    borderRadius: 16,
    photoGap: 6,
    photoBorderRadius: 8,
    showDate: false,
    showCaption: true,
    dateFont: "system",
    captionFont: "PressStart2P",
    textColor: "#FFFFFF",
    overlayKey: "y2k-stars",
    overlayOpacity: 0.55,
    thumbnail: "y2k",
  },
  {
    id: "film",
    name: "Film",
    tags: ["analog", "lo-fi", "warm"],
    format: "both",
    backgroundColor: "#F5E6D0",
    borderColor: "#2C1810",
    borderWidth: 12,
    borderRadius: 4,
    photoGap: 2,
    photoBorderRadius: 2,
    showDate: true,
    showCaption: true,
    dateFont: "SpaceMono-Bold",
    captionFont: "SpaceMono-Regular",
    textColor: "#2C1810",
    overlayKey: "film-grain",
    overlayOpacity: 0.4,
    thumbnail: "film",
  },
  {
    id: "dark",
    name: "Dark",
    tags: ["moody", "aesthetic", "noir"],
    format: "both",
    backgroundColor: "#0A0A0A",
    borderColor: "#C9A84C",
    borderWidth: 8,
    borderRadius: 4,
    photoGap: 4,
    photoBorderRadius: 2,
    showDate: true,
    showCaption: true,
    dateFont: "SpaceMono-Bold",
    captionFont: "Caveat",
    textColor: "#C9A84C",
    overlayKey: "dark-vignette",
    overlayOpacity: 1,
    thumbnail: "dark",
  },
  {
    id: "pastel",
    name: "Pastel",
    tags: ["soft", "cute", "dreamy"],
    format: "both",
    backgroundColor: "#E8F4F8",
    borderColor: "#B8D8E8",
    borderWidth: 10,
    borderRadius: 20,
    photoGap: 6,
    photoBorderRadius: 8,
    showDate: true,
    showCaption: true,
    dateFont: "SpaceMono-Regular",
    captionFont: "DancingScript",
    textColor: "#6B9EAF",
    overlayKey: "pastel-sparkles",
    overlayOpacity: 0.85,
    thumbnail: "pastel",
  },
];

export const getTemplateById = (id: string): Template | undefined =>
  TEMPLATES.find((t) => t.id === id);
